name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ 09031c1bb87b6f1dbd83cc13831c5778 }}
          TIMEZONE: Asia/Seoul
